name: Android, Wear and JVM CI

on: pull_request

# Cancel any current or previous job from the same PR
concurrency:
  group: android-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: :androidApp:assembleDebug :wearApp:assembleDebug :wearApp:assembleAndroidTest :shared:runJvmMain

    - name: Wear Unit Tests
      uses: gradle/gradle-build-action@v2
      with:
        arguments: :wearApp:testDebugUnitTest
