name: Backend Deploy

on:
  push:
    branches:
      - 'main'
    paths:
      - 'backend/**'
      - ".github/workflows/**"

# Cancel any current or previous job from the same PR
concurrency:
  group: backend-deploy-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: |
        echo ${{ secrets.APOLLO_KEY }} > backend/service-graphql/src/main/resources/apollo.key
        ./gradlew :backend:setupGoogleServices
        ./gradlew appengineDeploy
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}



