name: iOS CI

on: pull_request

# Cancel any current or previous job from the same PR
concurrency:
  group: ios-${{ github.head_ref }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.0.app && /usr/bin/xcodebuild -version
      - name: Build iOS app
        run: xcodebuild -project iosApp/iosApp.xcodeproj -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 8' build