name: iOS Publish
on:
  workflow_dispatch:
#  push:
#    branches:
#      - "main"

env:
  MAVEN_USERNAME: ${{ secrets.REPSY_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.REPSY_PASSWORD }}

jobs:
  call-kmmbridge-publish:
    permissions:
      contents: write
      packages: write
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildautoversion.yml@v1.1
    with:
      jvmVersion: 17
      versionBaseProperty: LIBRARY_VERSION
    secrets:
      gradle_params: -DMAVEN_USERNAME=${{env.MAVEN_USERNAME}} -DMAVEN_PASSWORD=${{env.MAVEN_PASSWORD}}