name: Update GraphQL schema
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: apollographql/update-graphql-schema@main
        with:
          endpoint: "https://confetti-349319.uw.r.appspot.com/graphql"
          schema: "shared/src/commonMain/graphql/schema.graphqls"
