name: Update GraphQL schema
on:
  schedule:
    - cron: "0 0 * * *"
#  pull_request

jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: apollographql/update-graphql-schema@59d4aa970db7d8559e48a5ddc5b3c09c052c88b0
        with:
          endpoint: "https://confetti-app.dev/graphql"
          schema: "shared/src/commonMain/graphql/schema.graphqls"
          github_token: ${{ secrets.GITHUB_TOKEN }}
