name: Android, Wear and JVM CI

on:
  pull_request:
  workflow_dispatch:

# Cancel any current or previous job from the same PR
concurrency:
  group: wear-instrumentation-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    # TODO change to a test specific label
    #if: contains(github.event.pull_request.labels.*.name, 'enhancement')
    timeout-minutes: 50

    strategy:
      matrix:
        api-level: [ 30 ]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

      # TODO move to the android_wear_jvm.yml
    - name: Unit Tests
      uses: gradle/gradle-build-action@v2
      with:
        arguments: :wearApp:test

    - name: AVD cache
      uses: actions/cache@v3
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-${{ matrix.api-level }}

    - name: Create AVD and generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        script: echo "Generated AVD snapshot for caching."

    - name: Instrumentation Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        script: ./gradlew :wearApp:connectedCheck
      env:
        API_LEVEL: ${{ matrix.api-level }}
